server:
    port: 8080
    session:
        cookie:
            name: ui-session
    
security:
    oauth2:
        client:
            client-id: web
            client-secret: secret
            access-token-uri: http://localhost:8081/auth/oauth/token
            user-authorization-uri: http://localhost:8081/auth/oauth/authorize
        resource:
            user-info-uri: http://localhost:8081/auth/me
    
zuul: 
    routes:
        resource:
            path: /home
            url: http://localhost:8082/
        auth:
            path: /me
            url: http://localhost:8081/auth
            
logging:
    level:
        org.springframework.security: DEBUG