server:
    port: 8080
    session:
        cookie:
            name: ui-session
            
spring.application.name: gateway            
    
security:
    oauth2:
        client:
            client-id: web
            client-secret: secret
            access-token-uri: http://localhost:8080/auth/oauth/token
            user-authorization-uri: http://localhost:8080/auth/oauth/authorize
        resource:
            jwt.key-value: test
    
zuul:
    routes:
        resource:
            path: /home
            url: http://localhost:8082/
        auth-server:
            path: /auth/**
            stripPrefix: false
            sensitiveHeaders:
        resource-server:
            path: /home/**
    add-host-header: true

logging:
    level:
        org.springframework.security: DEBUG
        org.springframework.cloud.netflix.zuul: DEBUG